# ================================================================================
# DOCKER COMPOSE BASE - compose.yaml
# ================================================================================
# Utilisé en développement avec compose.override.yaml
# Utilisé en production avec compose.prod.yaml
# ================================================================================

services:
  # Application Symfony (configuration de base)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}  # production en prod, development en dev
    container_name: villereau_app
    networks:
      - app-network
    volumes:
      # Code source (seulement en développement via override)
      - .:/var/www/symfony
    environment:
      - APP_ENV=${APP_ENV:-dev}
    depends_on:
      database:
        condition: service_healthy

  # Base de données MySQL (configuration commune)
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: villereau_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-!ChangeMe!}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - app-network

# Réseaux
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  database_data:
    driver: local
