# ================================================================================
# DOCKER COMPOSE BASE - compose.yaml
# ================================================================================
# Utilisé en développement avec compose.override.yaml
# Utilisé en production avec compose.prod.yaml
# ================================================================================

services:
  # Application Symfony (configuration de base)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}  # production en prod, development en dev
    container_name: villereau_app
    networks:
      - app-network
    volumes:
      # Code source (seulement en développement via override)
      - .:/var/www/symfony
    environment:
      - APP_ENV=${APP_ENV:-dev}
    depends_on:
      database:
        condition: service_healthy

  # Base de données PostgreSQL (configuration commune)
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: villereau_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

# Réseaux
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  database_data:
    driver: local
