monolog:
    handlers:
        # Application logs
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: warning
            max_files: 30
            channels: ["!event"]
            
        # Error logs
        error:
            type: rotating_file
            path: '%kernel.logs_dir%/error.log'
            level: error
            max_files: 30
            
        # Security logs
        security:
            type: rotating_file
            path: '%kernel.logs_dir%/security.log'
            level: info
            channels: ["security"]
            max_files: 30
            
        # Console command logs
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stdout
                level: debug 