controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

mon_espace:
    path: /mon-espace
    controller: App\Controller\MonEspaceController::index
